"""add programme to user

Revision ID: 44c6673f1f94
Revises: 8bfd9ddd6643
Create Date: 2025-10-22 19:01:39.604321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c6673f1f94'
down_revision: Union[str, None] = '8bfd9ddd6643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
