"""Make user_type nullable in checkins

Revision ID: 69e1fbad11e3
Revises: 7a565dbc420e
Create Date: 2025-11-01 20:27:36.844217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69e1fbad11e3'
down_revision: Union[str, None] = '7a565dbc420e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'user_type',
               existing_type=postgresql.ENUM('EMPLOYEE', 'VISITOR', name='usertype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'user_type',
               existing_type=postgresql.ENUM('EMPLOYEE', 'VISITOR', name='usertype'),
               nullable=False)
    # ### end Alembic commands ###
