"""init schema

Revision ID: 7836d6977b2a
Revises: 
Create Date: 2025-10-22 17:50:36.421523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7836d6977b2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('floors_count', sa.Integer(), nullable=False),
    sa.Column('blocks_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_building_code'), 'buildings', ['building_code'], unique=True)
    op.create_table('security_officers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_pin', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number')
    )
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('block_label', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'block_label', name='uq_building_block_label')
    )
    op.create_table('floors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('floor_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'floor_index', name='uq_building_floor_index')
    )
    op.create_table('spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DESK', 'OFFICE', 'ROOM', name='spacetype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'type', name='uq_building_space_type')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('programme', sa.String(length=100), nullable=True),
    sa.Column('laptop_model', sa.String(length=200), nullable=True),
    sa.Column('laptop_asset_number', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=True),
    sa.Column('guest_emails', sa.Text(), nullable=True),
    sa.Column('notify_guests', sa.Boolean(), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('start_time < end_time', name='ck_booking_start_before_end'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('registered_laptop', sa.String(length=200), nullable=True),
    sa.Column('registered_asset_number', sa.String(length=100), nullable=True),
    sa.Column('checked_in_laptop', sa.String(length=200), nullable=True),
    sa.Column('checked_in_asset_number', sa.String(length=100), nullable=True),
    sa.Column('is_match', sa.Boolean(), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('floor', sa.String(length=100), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('check_in_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_in_time', sa.Time(timezone=True), nullable=True),
    sa.Column('check_out_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.Time(timezone=True), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('checked_out_by_officer', sa.String(length=200), nullable=True),
    sa.Column('officer_badge', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('CHECKED_IN', 'CHECKED_OUT', name='checkinstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=True),
    sa.Column('host_employee_id', sa.UUID(), nullable=True),
    sa.Column('host_employee_name', sa.String(length=200), nullable=True),
    sa.Column('other_reason', sa.String(length=500), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('block', sa.String(length=50), nullable=True),
    sa.Column('has_weapons', sa.Boolean(), nullable=True),
    sa.Column('weapon_details', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_employee_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('user_type', sa.Enum('EMPLOYEE', 'VISITOR', name='usertype'), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('floor', sa.String(length=100), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('laptop_model', sa.String(length=200), nullable=True),
    sa.Column('laptop_asset_number', sa.String(length=100), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CHECKED_IN', 'CHECKED_OUT', name='checkinstatus'), nullable=True),
    sa.Column('qr_code_data', sa.String(length=500), nullable=True),
    sa.CheckConstraint('((user_id IS NOT NULL)::integer + (visitor_id IS NOT NULL)::integer) = 1', name='ck_checkin_user_xor_visitor'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkins')
    op.drop_table('visitors')
    op.drop_table('laptop_records')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('spaces')
    op.drop_table('floors')
    op.drop_table('blocks')
    op.drop_table('security_officers')
    op.drop_index(op.f('ix_buildings_building_code'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
