"""Add expires_at to checkins

Revision ID: 7a565dbc420e
Revises: 98cf45de0b9e
Create Date: 2025-11-01 20:23:55.925732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a565dbc420e'
down_revision: Union[str, None] = '98cf45de0b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('laptop_records', 'checked_in_laptop')
    op.drop_column('laptop_records', 'checked_in_asset_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptop_records', sa.Column('checked_in_asset_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('laptop_records', sa.Column('checked_in_laptop', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('checkins', 'expires_at')
    # ### end Alembic commands ###
